### ISSUE TITLE
add max width to contact form textarea

### ISSUE THREAD

**Issue by ralfz123** [DikkeTimo/fix-the-flow-interactive-website#3]
Add max width to textarea, otherwise you get it like the screenshot

Add to the textarea the style `    max-width: 100%;`. It listens to its container (fieldset).
<img width="678" alt="image" src="https://user-images.githubusercontent.com/55750121/206291472-562b0ab0-9191-477f-8703-e552f6a4393b.png">

**Comment by DikkeTimo** [comment]
Fixed, thanks!
